lptaylor/LittleShop

- app/controllers/root_controller.rb
- app/views/root/index.html.erb
- spec/features/visitor_sees_a_navigation_page_spec.rb
Resolves #79 / #74 
Needs sad path testing
User Story 2: 
As a visitor
I see a navigation bar
This navigation bar includes links for the following:
- a link to return to the welcome / home page of the application ("/")
- a link to browse all items for sale ("/items")
- a link to see all merchants ("/merchants")
- a link to my shopping cart ("/cart")
- a link to log in ("/login")
- a link to the user registration page ("/register")
Next to the shopping cart link I see a count of the items in my cart
> User-story 2: visitor navigation

- app/controllers/admin/users_controller.rb
- app/models/user.rb
- app/views/admin/users/index.html.erb
- app/views/root/index.html.erb
- config/routes.rb
- db/migrate/20181217221509_add_role_to_users.rb
- spec/features/admin_sees_all_users_spec.rb
- spec/features/visitor_sees_a_navigation_page_spec.rb
- spec/models/user_spec.rb
Updated test for happy/sad path, User Model with enum parameters, all tests pass for namespacing admin to see all users, updated method on Admin Users controller for index.
> Groupcheckin

- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/models/item.rb
- app/models/user.rb
- app/views/admin/users/index.html.erb
- app/views/sessions/new.html.erb
- app/views/users/new.html.erb
- app/views/users/show.html.erb
- db/migrate/20181216210855_create_items.rb
- db/migrate/20181218225345_remove_username_from_users.rb
- db/schema.rb
- spec/factories/user_factory.rb
- spec/features/admin_sees_all_users_spec.rb
- spec/features/user_can_login_and_logout_spec.rb
- spec/features/user_can_register_for_site_spec.rb
- spec/features/visitor_sees_a_navigation_page_spec.rb
- spec/models/item_spec.rb
- spec/models/user_spec.rb
Removes "username" from the users table in the database, app & tests.  
Updates image field in items tables to "image_url".
Updates price field type from "integer" to "decimal" in the database.
Finally changes the "qty_in_stock" field in the items table, app & tests to now be "inventory".
All tests are passing.
> Updates database names

- spec/factories/item_factory.rb
- spec/models/item_spec.rb
May cause git fire. Factorybot now will make items and they will always be associated to a merchant role as the user has had a role set as an override.
> adds working factory bot for items and merchant association confirmed

- app/views/users/new.html.erb
- db/migrate/20181217221447_add_name_to_users.rb
- db/migrate/20181217221447_add_username_to_users.rb
- db/migrate/20181218225345_remove_username_from_users.rb
- db/schema.rb
- spec/factories/user_factory.rb
- spec/features/user_can_register_for_site_spec.rb
Adds "name" to the Users table in the database, in our tests & in the app itself.  All tests are passing.
> Adds "name" field to Users Table

- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/layouts/application.html.erb
- app/views/users/new.html.erb
- spec/features/user_can_register_for_site_spec.rb
Resolves #68 
Added testing for the flash message for successful login & registration of a user.
> 68 user registration two

- app/views/users/show.html.erb
- spec/features/user_sees_data_on_profile_page_spec.rb
Adds passing test and implemented code for getting user data to display on the user profile page.
(still need to add edit link on this page to finish out the waffle.)
> 55 user profile page

- app/controllers/sessions_controller.rb
- spec/features/users/user_can_login_and_logout_spec.rb
> finishes path testing and flash messages for user_story 10

- spec/features/cart/user_can_item_to_cart_spec.rb
- spec/models/cart_spec.rb
> #45- Adds Items to Cart

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/items.scss
- app/views/items/index.html.erb
- spec/features/users/user_can_see_all_items_spec.rb
Completes remaining parts of User Story 14 except:
- I see all items in the system except disabled items
All tests passing
User Story 14: Items Index Page
As any kind of user on the system
I can visit the items catalog ("/items")
**I see all items in the system except disabled items**
Each item will display the following information:
- the name of the item
- a small thumbnail image for the item
- the merchant name who sells the item
- how many of the item the merchant has in stock
- the merchant's current price for the item
The item name is a link to that item's show page
The item thumbnail is a link to that item's show page
> Items Index Page

- app/controllers/sessions_controller.rb
- spec/features/admins/admin_nav_spec.rb
- spec/features/merchants/merchant_can_nav_to_dashboard_spec.rb
- spec/features/users/user_can_login_and_logout_spec.rb
- spec/features/visitors/visitor_can_register_for_site_spec.rb
closes #62 
Adds redirect and flash message for if your logged in as any type of user, and navigate to the login_path.
This finishes user story 12.
> User story 12

- app/controllers/admin/users_controller.rb
- app/views/admin/users/show.html.erb
- spec/features/admins/admin_nav_spec.rb
closes #51 
Adds passing test and code for an admin to be able to see a registered user's profile page.
I made sure to do sad path testing as well.
> User story 21

- app/controllers/admin/users_controller.rb
- app/controllers/users_controller.rb
- app/views/admin/users/show.html.erb
- app/views/users/edit.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- spec/features/admins/admin_nav_spec.rb
- spec/features/users/user_can_edit_profile_spec.rb
closes #53 
Adds passing test for a user to edit their profile page and see a successful flash message.
Had to update our edit_profile_path route to be correct & made sure to sad path test.
> User story 19

- app/controllers/carts_controller.rb
- app/views/carts/index.html.erb
- config/routes.rb
- spec/features/cart/user_can_item_to_cart_spec.rb
closes #43 
closes #42 
Changed '/cart' to index page from show, and updated routes to hand-roll cart because resoureces wasn't working. Updated index page to show message is params are empty and also added link for deleting all items. Also created destroy method on carts_controller. 
Please review, thanks guys
43
As a visitor or registered user
When I add NO items to my cart yet
And I visit my cart ("/cart")
I see a message that my cart is empty
I do NOT see the link to empty my cart
42
As a visitor or registered user
When I have items in my cart
And I visit my cart ("/cart")
And I click the link to empty my cart
Then I am returned to my cart
All items have been completely removed from my cart
The navigation bar shows 0 items in my cart
> User story 28 and 29

- app/controllers/merchants_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/users/index.html.erb
- spec/features/visitors/visitor_can_register_for_site_spec.rb
- spec/features/visitors/visitor_can_see_all_active_merchants_spec.rb
- spec/models/user_spec.rb
closes #23 finishes basic merchant index page with feature and model testing.
> #23 story 45

- app/controllers/application_controller.rb
- app/controllers/dashboard_controller.rb
- app/views/dashboard/show.html.erb
- spec/features/merchants/merchant_can_nav_to_dashboard_spec.rb
- spec/features/visitors/visitor_can_see_all_active_merchants_spec.rb
completes basic profile information for Merchant dashboard show. More content to be added in coming user stories.
> #31 merch dashboard page

- app/controllers/orders_controller.rb
- app/controllers/profile/orders_controller.rb
- app/models/order.rb
- app/models/order_item.rb
- app/views/orders/index.html.erb
- app/views/orders/show.html.erb
- app/views/profile/orders/index.html.erb
- app/views/profile/orders/show.html.erb
- config/routes.rb
- db/migrate/20181222211245_add_columns_to_order_items.rb
- db/schema.rb
- spec/factories/order_factory.rb
- spec/factories/order_item_factory.rb
- spec/features/orders/user_can_view_order_show_page_spec.rb
- spec/models/order_items_spec.rb
- spec/models/order_spec.rb
Closes #37 and completes user story 33. 
- The routes were updated to namespace out orders, pretty sure this conflicts with one of justins PRs.  I moved a few of the view files around to account for the namespacing, but didn't delete the originals.  We'll need to go back and clean up that if you guys think these changes will work.
- Added price and quantity columns to the order_items  table.  Is it possible to link the item price to the price on the order items table?
- The images aren't appearing.. not totally sure why. I made of a lot of db changes and just waiting to seed again until I add in the order and order_items info into the seed file.
_______
User Story 33
As a registered user
When I visit my profile page
And I click on a link for order's show page
My URL route is now something …
> #33 user views order show

- app/models/cart.rb
- app/models/item.rb
- app/views/carts/index.html.erb
- app/views/carts/show.html.erb
- spec/features/cart/user_can_add_item_to_cart_spec.rb
- spec/models/cart_spec.rb
- spec/models/item_spec.rb
closes #44 
Took a bit to work out the testing and total single item vrs full cart. But created model and feature tests. Please review, all tests pass
As a visitor or registered user
When I have added items to my cart
And I visit my cart ("/cart")
I see all items I've added to my cart
And I see a link to empty my cart
Each item in my cart shows the following information:
- the name of the item
- a very small thumbnail image of the item
- the merchant I'm buying this item from
- the price of the item
- my desired quantity of the item
- a subtotal (price multiplied by quantity)
I also see a grand total of what everything in my cart will cost
> User story 27

- app/controllers/profile/orders_controller.rb
- app/views/users/show.html.erb
- spec/features/orders/user_profile_shows_all_orders_spec.rb
Closes #54 
All tests passing, includes sad path testing.
-------
User Story 18, User Profile displays Orders
As a registered user
When I visit my profile page
If my account has ordered items
I see every order I've made, which includes the following information:
- the ID of the order, which is a link to the order show page
- the date the order was made
- the date the order was last updated
- the current status of the order
- the total quantity of items in the order
- the grand total of all items for that order
> User Story 18- User Profile Displays Orders

- app/controllers/dashboard/items_controller.rb
- app/controllers/dashboard_controller.rb
- app/views/dashboard/items/index.html.erb
- app/views/dashboard/show.html.erb
- spec/features/merchants/merchant_can_nav_to_own_items_and_see_them_spec.rb
Adds the path for a merchant to view all of their items as well as the testing to make sure the link is going to the correct path. I did over do it a bit and incorporated some stuff fro the next story
> User story 41 #28

- app/assets/stylesheets/application.scss
- app/views/items/index.html.erb
- app/views/layouts/application.html.erb
- app/views/root/index.html.erb
- app/views/sessions/new.html.erb
- app/views/users/edit.html.erb
- app/views/users/index.html.erb
- app/views/users/new.html.erb
This is just some basic CSS I added to the app.
I just added "div"s around elements in the nav bar, and reordered where they show up in the nav bar.
Also, I removed all the "Scaffold" formatting in the item index page, but didn't remove any of the logic.
> Adds initial css for styling the app.

- app/controllers/carts_controller.rb
- app/models/cart.rb
- app/views/carts/index.html.erb
- config/routes.rb
- spec/features/cart/user_can_add_item_to_cart_spec.rb
- spec/features/cart/user_can_remove_items_spec.rb
- spec/models/cart_spec.rb
Closes #41 
All tests still pass, added buttons to increment item based on inventory and minus button as well. Model tests and Features pass 99% overall coverage
As a visitor or registered user
When I have items in my cart
And I visit my cart
Next to each item in my cart
I see a button or link to remove that item from my cart
- clicking this button will remove the item but not other items
I see a button or link to increment the count of items I want to purchase
- I cannot increment the count beyond the merchant's inventory size
I see a button or link to decrement the count of items I want to purchase
- If I decrement the count to 0 the item is immediately removed from my cart
> User story 30

- app/controllers/sessions_controller.rb
- app/views/carts/index.html.erb
- spec/features/users/any_user_can_logout_spec.rb
- spec/features/visitors/visitor_sees_register_login_incart_spec.rb
closes #61  
As a registered user, merchant, or admin
When I visit the logout path
I am redirected to the root page of the site
And I see a flash message that indicates I am logged out
Any items I had in my shopping cart are deleted
closes #40  
As a visitor
When I have items in my cart
And I visit my cart
I see information telling me I must register or log in to finish the checkout process
The word "register" is a link to the registration page
The words "log in" is a link to the login page
> User story 31

- app/controllers/orders_controller.rb
- app/controllers/users_controller.rb
- app/views/profile/orders/index.html.erb
- spec/features/cart/user_can_remove_items_spec.rb
- spec/features/users/registered_user_can_checkout_spec.rb
- spec/features/users/user_can_edit_profile_spec.rb
Doesn't close user_story 35 but fixes bugs for email error and half of story 35 complete.
> Fixes bugs

- app/controllers/dashboard/items_controller.rb
- app/views/dashboard/items/index.html.erb
- spec/factories/item_factory.rb
- spec/features/merchants/merchant_can_nav_to_own_items_and_see_them_spec.rb
finishes story 53 for merch can delete item and gets conf flash message.
> User story 53 #14

- app/controllers/admin/merchants_controller.rb
- app/models/user.rb
- app/views/admin/merchants/index.html.erb
- config/routes.rb
- spec/features/admins/admin_sees_all_merchants_spec.rb
- spec/models/user_spec.rb
closes #21 
Adds passing feature & model test for an admin to see all merchants.
Added "admin_merchants_path" to controllers & added "merchants" method to the users model.
> User story 47

- app/controllers/application_controller.rb
- app/controllers/orders_controller.rb
- app/controllers/profile/orders_controller.rb
- app/models/order.rb
- app/views/items/index.html.erb
- app/views/profile/orders/index.html.erb
- spec/features/users/registered_user_can_checkout_spec.rb
- spec/features/visitors/visitor_can_see_all_active_merchants_spec.rb
Update cart for create in profile/orders_controller and destroy in orders_controller 
Took a bit to implement change for create but all tests are passing. For some reason, rails is giving an error about root controller#index not being able to find id in the application controller. Can't view, is anyone else having this problem?
> Update cart for create / destroy

- app/controllers/application_controller.rb
- app/views/admin/users/show.html.erb
- config/routes.rb
- spec/features/admins/admin_sees_users_orders_spec.rb
Updates User Story 23, Admin sees user's orders for changes to user profile page.
Adds helper method current_admin
> Admin orders

- app/controllers/admin/orders_controller.rb
- app/views/admin/orders/show.html.erb
- app/views/profile/orders/index.html.erb
- app/views/users/show.html.erb
- spec/features/admins/admin_sees_orders_show_page_spec.rb
- spec/features/orders/user_profile_shows_all_orders_spec.rb
Closes #36 
All new tests passing.  Have 3 new failing tests for some reason though:
1) Registered User when logged in if order is pending, user sees a link to cancel order
Failure/Error: expect(page).to have_link("Cancel Order")
expected to find link "Cancel Order" but there were no matches
2) Registered User when logged in can see full order with a status of pending
Failure/Error: expect(page).to have_content("Order status pending")
3) User class methods will return only registered users
Failure/Error: expect(User.registered_users).to eq([user_1, user_2, user_3])
User Story 34- Admin views a User's Order Show Page
As an admin user
When I visit a user's profile
And I click on a link for order's show page
My URL route is now something like "/admin/orders/15"
I see all information about …
> User story 34

- app/controllers/admin/users_controller.rb
- app/models/user.rb
- app/views/admin/users/index.html.erb
- spec/features/admins/admin_disables_registered_user_spec.rb
closes #1  & closes #2 
Finally got the enable/disable feature to work!
User Story 63, Admin disables a user account
User Story 64, Admin enables a user account
> User story 63 & 64

- app/controllers/dashboard/items_controller.rb
- app/controllers/items_controller.rb
- app/controllers/orders_controller.rb
- app/models/item.rb
- app/views/dashboard/items/edit.html.erb
- app/views/dashboard/items/new.html.erb
- app/views/profile/orders/index.html.erb
- spec/features/merchants/merchant_can_nav_to_own_items_and_see_them_spec.rb
- spec/models/item_spec.rb
closes all #11 #10 #12 #13 #14 #16 #15
> Merch crud stories

- spec/features/visitors/visitor_can_see_all_active_merchants_spec.rb
> fixes outstanding test issue

- app/controllers/items_controller.rb
- app/models/item.rb
- app/views/items/index.html.erb
- spec/features/items/user_sees_stats_about_items_spec.rb
Closes #58 
All tests passing, includes sad path testing
User Story 15, Items Index Page Statistics
As any kind of user on the system
When I visit the items index page ("/items")
I see an area with statistics:
- the top 5 most popular items
- the bottom 5 least popular items
> Items stats

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/cart.scss
- app/assets/stylesheets/users.scss
- app/views/carts/index.html.erb
- app/views/users/show.html.erb
- spec/features/cart/user_can_add_item_to_cart_spec.rb
This is the new CSS & styling for the shopping cart.
Made sure all tests were fixed and passing after changes.
> Adds new CSS & styling for cart.
